# title: "Safety Representations for Safer Policy Learning"
# description: Learning state-centric safety representations to enable safer and more efficient reinforcement learning through improved risk-reward tradeoffs.<br> Work by <a href="https://github.com/manila95">Kaustubh Mani</a>, <a href="https://scholar.google.ca/citations?user=62a5KoUAAAAJ&hl=en">Vincent Mai</a>, <a href="https://velythyl.github.io/">Charlie Gauthier</a>, <a href="https://anniesch.github.io/">Annie S. Chen</a>, <a href="https://samernashed.github.io/">Samer Nashed</a>, <a href="https://liampaull.ca/">Liam Paull</a><br><br> ICLR 2025
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub Pages configuration
github: [metadata]
repository: montrealrobotics/srpl
branch: main

# links:
#   arxiv: https://arxiv.org/pdf/2502.20341
#   code: https://github.com/montrealrobotics/srpl/
  # video: https://www.youtube.com/watch?v=oH99fd_462Q
