# title: ""  # Empty title to prevent theme header
# description: ""  # Empty description to prevent theme header
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# GitHub Pages configuration
github: [metadata]
repository: montrealrobotics/srpl
branch: main

# links:
#   arxiv: https://arxiv.org/pdf/2502.20341
#   code: https://github.com/montrealrobotics/srpl/
  # video: https://www.youtube.com/watch?v=oH99fd_462Q
